### PR TITLE
client should be able to specify cookie path in settings

### PR DESCRIPTION
**Pull request by lloyd**
allow the client of the module to specify the cookie path, useful to reduce network overhead and to limit the transmission of the cookie

### CODE REVIEW

**Comment by caolan** [comment]
Hey lloyd, this looks great :) ...would you mind writing a test to go with it?

**Comment by lloyd** [comment]
Sure thing, I can give that a run sometime in the next day or so.  beautiful module, btw.  thanks for writing it.

**Comment by caolan** [comment]
I've added tests and documentation, thanks again :)

**Comment by lloyd** [comment]
oh awesome!  sorry for not finishing the contribution, and thanks for picking up the slack!

**Pull request merged**
